### ISSUE TITLE
Mining speed too quick.

### ISSUE THREAD

**Issue by Shadaez** [jrbudda/Vivecraft_111#1]
Seems to be twice as fast as it should be. Standing mode.

**Comment by jrbudda** [comment]
fixed ty, build available in discord

**Comment by Shadaez** [comment]
still happening for me in r2, there's like no delay between when you destroy blocks like there should be, but individual block mining seems fine

**Comment by Shadaez** [comment]
OK, my friend has the same issue on vanilla, but I don't have it on vanilla outside of VR. Maybe it's not a vivecraft issue.
